### ISSUE TITLE
A task with confirm: true wont work

### ISSUE THREAD

**Issue by HeyListenNavi** [moustacheful/myrmidon#11]
So i have a task that uses the confirm option but i just wont work, i tried to run the task from the terminal and it shows this message:
`config/rofi/myrmidon.sh: line 25: config/rofi/confirm.sh: Permission denied`
should i move the files to another folder(i already tried moving the files to the home folder)?

pd: sorry for my bad english >,<

**Comment by moustacheful** [comment]
Hey @ErickGuzmanOchoa I think you're probably missing giving the shell files execution permissions, try doing

```
chmod +x ./path-to-myrmidon/myrmidon.sh
chmod +x ./path-to-myrmidon/confirm.sh
```

Obviously change the paths to reflect the actual location of the shell files!

Try that and let me know if it resolves the issue. I might have omitted that on the readme.
(and your english is pretty good! don't apologize!)

**Comment by HeyListenNavi** [comment]
Thanks :3, it works perfectly now :)
